### ISSUE TITLE
Filtering of value sets and code systems for IG display

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr-fhir-export#104]
We need a meaningful filter for listing value sets in IGs. There is no consistency on how existing FHIR IGs approach this. Some options:

**Option 1. list only what _is defined_ in the IG, i.e., local value sets and local code systems**. This is helpful for readers to pinpoint our creations, but doesn't provide a comprehensive overview of the terminology used by the IG.

**Option 2. List everything _used_ in the IG, i.e., all locally and externally defined value sets and code systems**. This would provide a comprehensive view of the terminology used in our IG, but we have some limitations:
1. Including all referenced value sets is confusing to the reader, since some of them are secondary to the core content of the IG
2. We can't currently identify the code systems used by external value sets without integrating with their associated vocabulary services.

**Option 3. The best approximation we can currently produce of option 2** plus a note explaining that code systems for external value sets are not included.

I suggest we go with option 3. @markkramerus, @mlterryMitre, @cmoesel, any objections?

**Comment by cmoesel** [comment]
Note a few other downsides of option 2/3 to consider:
* We only have a URL for external value set bindings -- no name, description, etc. So that's what the user may see -- just the URL
    * If the value set is defined by core FHIR spec or US Core, we _may_ be able to lookup the name in our local definition files
    * If we want to invest, we may be able to parse URLs to put something more meaningful (e.g., detect if it's VSAC or PHIN VADS and put text "VSAC 0123567890", etc)
* Value Set URLs are not guaranteed to resolve.  So if we try to link them, note that the links may be broken.  The IG Publisher will whine about these broken links.

**Comment by rutemartins** [comment]
Good points, Chris. I think we should recognize these limitations, and was envisioning listing the URLs only for external value sets. As for URLs not resolving, I'd say that's a bug that we need to solve.

**Comment by cmoesel** [comment]
@kjmahalingam is right.  As far as external value sets go, there's not much we can do if the URL doesn't resolve.  We don't control the URL (since it's external) and we don't control the value set content or where it's hosted (since it's external).

**Comment by rutemartins** [comment]
@cmoesel why would a URL not revolve if it is the correct one? Can you give an example?

**Comment by kjmahalingam** [comment]
@cmoesel @rutemartins Just reigniting this thread, in an effort to move forward with a solution.

**Comment by cmoesel** [comment]
@kjmahalingam's  PR looks good, but I don't think we resolved the URL resolution issue (no pun intended).  That's partially because I never answered @rutemartins's question:
> why would a URL not revolve if it is the correct one? Can you give an example?

The _primary_ purpose of a Value Set's URL is as a globally unique identifier.  While resolution is _preferred_, it is not _required_.  From the [FHIR spec](http://hl7.org/fhir/STU3/valueset-definitions.html#ValueSet.url):
> An absolute URI that is used to identify this value set when it is referenced in a specification, model, design or an instance. This SHALL be a URL, SHOULD be globally unique, and SHOULD be an address at which this value set is (or will be) published.

Unfortunately, there are plenty of value set URIs that don't resolve -- mostly from IGs (including ours).  I think this is actually due to the way FHIR publishes IGs.  For example, none of US Core's value sets resolve (try [http://hl7.org/fhir/us/core/ValueSet/us-core-problem](http://hl7.org/fhir/us/core/ValueSet/us-core-problem)).

Looking at the external value sets we use, it looks to me like the _core_ FHIR value sets mostly resolve and the LOINC value sets resolve (although you need to enter LOINC.org credentials).  We're also using three US Core value sets, none of which resolve.

So the question is: Should the external value sets listed in our IG be actual links (come of which will be broken), or should we just make them text?

**Comment by kjmahalingam** [comment]
Thanks for the response, @cmoesel.

I think @rutemartins should have the final say on the matter, but personally, I feel like it is worth it to keep the external value sets listed as actual links.

From a user perspective, I think that this allows for easy access to the value set resolution for those that do resolve, as opposed to requiring the user to copy-paste it. And for the value sets that do not resolve, a user could still copy-paste the URL and try to access it anyway, so I don't think writing a URL as text provides too much more protection.

I'm open to more discussion on the matter, though.

**Comment by cmoesel** [comment]
I hear your argument, @kjmahalingam -- and I think it makes sense.  One complication, however, is that the FHIR IG publisher scans the whole IG for broken links -- so non-resolving value set links will send up red flags.

We could mitigate it by adding special processing for known value set sources.  For example, we know US Core links don't resolve, but there is a simple algorithm to get from the _invalid_ link to a _valid_ one (e.g., `http://hl7.org/fhir/us/core/ValueSet/us-core-problem` --> `http://www.hl7.org/fhir/us/core/ValueSet-us-core-problem.html` -- see the pattern?)

We need to determine if it's worth the extra effort and complication.  We could just create a single function called `getValueSetLink` that combines my earlier idea and this one to return a full link (e.g., `getValueSetLink(http://hl7.org/fhir/us/core/ValueSet/us-core-problem)` returns `<a href="http://www.hl7.org/fhir/us/core/ValueSet-us-core-problem.html">US Core Problem Value Set</a>`).

**Comment by kjmahalingam** [comment]
@cmoesel, that makes sense, and the red flags dissuade me a bit. I think the question, then, is whether or not there is a guaranteed consistent way to get a valid value set link. This example for US Core links works well, but I assume there isn't a guaranteed method to find a valid link for every single value set from any given source, correct? Because by the FHIR spec as you quoted above, it seems as though there is not a requirement for a resolution at all. If there is not any guaranteed method to find a valid resolving link, perhaps it would be better to switch them to text as you said above, given the IG publishers red flags.

**Comment by rutemartins** [comment]
@cmoesel can we produce a list of URLs that fail to resolve? Are there any outside US Core? If US Core is the main issue, I'd say a `getValueSetLink` function makes sense. I've already opened a [gForge ticket](https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=17803) against  US Core, but I'm unsure whether this issue will be resolved before we publish another IG, so having a backup plan ready to go would be great.

**Comment by cmoesel** [comment]
Thanks for weighing in, @rutemartins. US Core value sets are the only problems in the breast cancer IG.  I'm not sure about the other IGs (ODH and Skin & Wound).  Still, I think I agree -- it's better to have a 99% solution than no solution at all.

@kjmahalingam -- what do you think?  Is this something you have time to tackle in this sprint (as part of this PR) or should it be a follow-on task?

**Comment by kjmahalingam** [comment]
Thanks to both @rutemartins and @cmoesel for the comments. I think it is worth adding this functionality in, after this discussion.

I think I can work to finish this in this sprint (hopefully relatively quickly). My other tasks are much larger, and I would rather get this out of the way before forgetting about it.
