### ISSUE TITLE
Potentially Mismatched Targets [Low priority]

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#34]
I'm not sure if this is a bug or not, but I'm getting the following warning:

 WARN shr: Potentially mismatched targets. Based on class (shr.core.Quantity) maps to Quantity. (module=shr-expand, shrId=shr.core.Duration, targetSpec=FHIR_STU_3, target=Duration)

Quantity...Quantity seems to match. Explanation?

**Comment by cmoesel** [comment]
This is probably another case of an error message that isn't explained thoroughly enough.  This warning is actually on the `Duration` element.  The tooling noticed that you mapped `Duration` to FHIR's `Duration`, but that Duration is _based on_ `Quantity`, which is mapped to a _different_ class (`Quantity`, of course).

In most cases if you map a sub-element to a different resource than it's parent, it's _probably_ a mistake.  That's why this warning exists.

In this case, however, it's obviously what we actually want.
