### ISSUE TITLE
Extraneous Warning Message: value[x] property not bound  when value is a Quantity [Low Priority]

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#36]
I'm getting warning messages that value[x] is not bound when using Quantity as a data type. For example:
		Element:		ExerciseHoursPerWeek
		Concept:		TBD
		Based on:	Observation
		Description:	"Hours of moderate or vigorous activity per week."
		Value:		Quantity 

results in:
[19:44:22.696Z]  WARN shr: The 'value[x]' property is not bound to a value set or fixed to a code. This property is core to the target resource and usually should be constrained. (module=shr-fhir-export, shrId=shr.behavior.ExerciseHoursPerWeek, target=Observation)

What I'm doing is constraining Observation.Value to be a Quantity. That should be OK, I think, and not generate the warning.

**Comment by cmoesel** [comment]
These warnings pop up on those quantities because we are assuming that if you require a `Quantity`, you should also specify the units you want.  In the cases where you see warnings, you haven’t done that.

In the example above, `ExerciseHoursPerWeek` should probably constrain the unit to UCUM's `h`.  For things that don't have a unit, however, you could either use the UCUM count unit (I think it is actually `1`) or we could have a `CountQuantity` profile that constrains out the units to `0..0`.

**Comment by cmoesel** [comment]
Warning updated to indicate it could be unconstrained Quantity units in shr-fhir-export v5.0.0-beta.4 and shr-cli v5.0.0-beta.5.
