### ISSUE TITLE
Which Classes are valid in Profiles?

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#47]
FHIR doesn't know anything about SHR class hierarchy. It doesn't know if an attribute can be a reference to class P, it could be a reference to class C, where C is a subclass of P (P=Parent, C=Child). We aren't taking that into account in our profiles. This will required some careful thought because some classes, like Observation, will have a ton of children.

**Comment by cmoesel** [comment]
While the FHIR doc isn't crystal clear on this, I think that when we specify a reference to class P (from your example above) -- that only indicates that the structure it points to must _conform_ to class P.  So... if it actually points to a structure of class C, and class C is a subclass of P, it's still OK -- because any subclass of P should still conform to P.  So, from a validation standpoint, I don't see an issue.

That said, if someone is going on FHIR profiles alone, there isn't a clear way for them to _know_ that class C is a subclass of class P.  So it would be difficult for them to read a profile that has a reference to class P, and know the full list of subclasses that are also viable.

It's possible we could have the profiles enumerate every viable sub-class as well (as a choice), but I don't think that's a feasible solution -- as it would be quite unwieldy when the reference is to something like Observation, which could have 100s (or 1000s) of viable subclasses.

**Comment by cmoesel** [comment]
BTW -- here's the [part of the FHIR doc](http://hl7.org/fhir/STU3/elementdefinition-definitions.html#ElementDefinition.type.targetProfile) that discusses references that specify profiles:

> *ElementDefinition.type.targetProfile*
> --
> Identifies a profile structure or implementation Guide that SHALL hold for the target of the reference this element refers to. Can be a local reference - to a contained StructureDefinition, or a reference to another StructureDefinition or Implementation Guide by a canonical URL. When an implementation guide is specified, the resource SHALL conform to at least one profile defined in the implementation guide.

It's not tremendously clear what _"SHALL hold"_ means, but further on, in the context of specifying an IG, it says _"SHALL conform"_.

**Comment by markkramerus** [comment]
Hmmm... Let's continue to track this and see if we're generating profiles that make sense. I'm not 100% convinced that we can rely of this. E.g., what happens if the class referred to is not an Entry Element, and there is no profile?

**Comment by markkramerus** [comment]
Moved to https://standardhealthrecord.atlassian.net/browse/CIMPL-45. Closing.
