### ISSUE TITLE
Why are Coding and CodeableConcept Profiled?

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#51]
There's no difference between SHR Coding and Coding, but the tooling is generating a profile:
http://standardhealthrecord.org/fhir/StructureDefinition-shr-core-CodeableConcept.html
Why does this profile exist?

(NOTE - In the past there was a difference, but to simplify the profiles, I eliminated all the differences.)

**Comment by cmoesel** [comment]
This is because those types are not native to SHR.  Anything that has a mapping will generate a profile.  Even though the structure of the profile is the same as the resource, it still holds some extra info, such as the SHR element it came from and the mapping definitions that were applied.

While we could probably implement some code to detect these situations, the use cases will be very rare -- and it will complicate implementation.  I think it would be better to invest in adopting these types natively, if that is what we're trying to emulate.

**Comment by markkramerus** [comment]
I'm not convinced. If I recall our previous discussions, we said that if SHR and FHIR structures are identical, then SHR should not generate a profile. What good is a profile with no diff?  The benefit would be hard to explain to users.

**Comment by cmoesel** [comment]
If I recall correctly, what we discussed before was centered on not _referencing_ profiles.  The profile would still be generated, but if it didn't contain any *required* changes (all changes were optional), then we said that perhaps we shouldn't require it to be called out as a reference explicitly.  But that was different because it applied to many more use cases (since we would be looking for no *required* differences rather than no differences at all) and it still generated the profile.  Also, I don't think we ever actually agreed that it was the right approach.

I'm not saying that we _can't_ detect no-diff profiles.  I'm just saying that true no-diff profiles will be few and far between, and right now it seems our only use case is for FHIR's complex types.  If we're really considering making those native, I think it's better just to invest in doing that (otherwise there is some duplicative effort).

That said, if you feel strongly about this I can look into it.

**Comment by cmoesel** [comment]
Support for "no-diff profiles" (or, to put it more correctly, the _supression_ of no-diff profiles) was added in `shr-fhir-export` v5.3.0.
