### ISSUE TITLE
Mappings fail to override a parent mapping

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#62]
Working on the Finding hierarchy, I came to the situation where a parent of Condition was mapped to Observation, and Condition itself was  mapped to http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition.  I thought the latter mapping would override the mapping of the parent class to Observation, but what actually happened was that the mapper tried to apply mapping from the parent class to the Condition mapping, which failed because target attributes from FHIR Observation aren't present in us-core-condition.  Here is a typical error message (there were many):

[17:28:10.078Z] ERROR shr: Invalid target path. Cannot apply cardinality constraint. ERROR_CODE:13013 (module=shr-fhir-export, shrId=shr.oncology.BreastCancer, mappingRule="constrain device to 0..0")
    target: http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition

What's obviously happening is that the mapper is walking up the class hierarchy and collecting all mappings for Condition from its SHR parents, then applying them. What should happen is, if the child class overrides the target resource, inherited mappings should be ignored.

**Comment by markkramerus** [comment]
To distinguish mapping overrides from an extended mapping, we should have a rule that if Foo is based on Bar, and Bar mapped to Baz, if you said "Foo maps to Baz:" or just "Foo:"** that would imply mappings should be  inherited, while "Foo maps to Qux:" would mean mappings should be overridden.  
**I believe that the syntax "Foo:" used to be acceptable, but now it causes an error.

**Comment by cmoesel** [comment]
This report covered two potential issues.  I've looked into both:

**I believe that the syntax "Foo:" used to be acceptable, but now it causes an error.**

I've tested this and I am unable to reproduce the issue.  I can successfully use `Foo:` in the mapping file, as long as `Foo` is based on an element that has an explicit mapping defined.

**Mapping inherits all mappings, even if BasedOn class maps to something else.**

At one point, this was intentional.  I know this because I found a unit test that actually tests that it *does* work like this.  I believe this is to allow for type hierarchies in the mapping target framework.

For example, imagine an SHR `Observation` element mapped to a FHIR `Observation`.  Now imagine an SHR `VitalSign` element mapped to a FHIR `VitalSign` profile on `Observation`.  Should the `VitalSign` mapping have to _redeclare_ every mapping rule that was in `Observation`, since it has a "different" mapping target?

When we first implemented the FHIR exporter, we needed this because of relationships like `Duration` being based on `Quantity`.  At the time, we didn't have logic to determine if the target FHIR `Duration` was based on the target FHIR `Quantity` -- so we let these things just pass through (with a warning).  Since then, however, we've added logic to be able to determine the inheritance hierarchies in FHIR too, so I think we may be able to address this.

What do you think of this?  Given `Foo based on Bar`, `Foo maps to TargetBoo`, and `Bar maps to TargetBaz`:
- if `TargetBoo` inherits from `TargetBaz`, then `Foo` mappings inherit `Bar` mappings.
- if `TargetBoo` does not inherit from `TargetBaz`, then `Foo` mappings do not inherit `Bar` mappings, and a warning is emitted.

If you agree, we can implement this as a fix.

**Comment by cmoesel** [comment]
This was implemented as proposed above with one minor difference: if the parent mapping is not compatible, it will not inherit it and it will only emit a _debug_ message (not a _warning_) since this is an expected use case.
